name: 'docker-image-name-action'
description:
  'Generate a docker image name for the current pull request or branch'
author: 'attention.tech'

inputs:
  baseName:
    description: 'the name of the docker image (without tag or :latest)'
    required: true

outputs:
  imageName:
    description: 'the docker image with generated tag'
  tag:
    description: 'generated tag'

runs:
  using: node20
  main: dist/index.js
